jobs:
  build:
    docker:
      - image: circleci/node:8.15-stretch-browsers-legacy
    working_directory: ~/project/
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: npm install
      - run:
          name: 'Push to UXPin'
          command: yarn run push
